---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.15.102
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.57.44
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.115.110
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      nginx_user_name: centos
