---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:nehardcore/vector-role.git
    scm: git
    version: "v1.1.1"
    name: vector
  - src: git@github.com:nehardcore/lighthouse-role.git
    scm: git
    version: "v2.2.2"
    name: lighthouse