---
- name: Install Nginx
  hosts: lighthouse
  tags: nginx
  handlers:
    - name: Start-nginx
      become: true
      ansible.builtin.command: nginx
    - name: Reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
  tasks:
    - name: NGINX | install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Start-nginx
    - name: NGINX | create general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Reload-nginx
- name: Install Lighthouse
  role: lighthouse
- name: Install Vector
  role: vector
- name: Install Clickhouse
  role: clickhouse
