---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.61.130
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.61.130
      ansible_user: centos
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 
      vector_config_dir: "{{ ansible_user_dir }}/vector_config"
      vector_config:
